### ISSUE TITLE
Different areas

### ISSUE THREAD

**Issue by gsharabok** [Mhttx2016/Multi-Camera-Object-Tracking-via-Transferring-Representation-to-Top-View#11]
Great project, the tracking, and reid work well when cameras are looking at the same area. Would like to ask whether anyone has figured out a way to make it work when cameras track different spaces?

**Comment by ahmadalzoubi13579** [comment]
hi @sharrik21 , i am working on similar idea where cameras track different places , can you tell me what the result of this repo in this  case? 
i do not want to modify the code a lot to figure out, and thank you.

**Comment by gsharabok** [comment]
Hey @gogoIsComing , it works well for the same area. So it is not initially aimed at larger areas and would take a lot of rethinking. Might be better to start somewhere else on this one.

**Comment by ahmadalzoubi13579** [comment]
@sharrik21 do you have any links or starting points for MTMC tracking across multiple non-overlapping cameras ???
this is the only similar project i found :
[MTMC across multiple non-overlapping cameras](https://www.youtube.com/watch?v=Rh8BUBBUUG8)

**Comment by gsharabok** [comment]
@gogoIsComing I have not found any good ones available. Ended up taking one of the projects I liked that was not made for non-overlapping cameras and combining with something else. So not much I can recommend here.

**Comment by ahmadalzoubi13579** [comment]
@sharrik21 can you mention some links about that `something else` ???, that will helps me a lot

**Comment by sry948749099** [comment]
> Great project, the tracking, and reid work well when cameras are looking at the same area. Would like to ask whether anyone has figured out a way to make it work when cameras track different spaces?

hello, I have completed the project and test on your own datasets.
Why are only one ID tracked when test on my own datasets? but there are seven persons in my datasets.
